version: "3.9"
services:
  fastjobs:
    build: .
    volumes:
      - ./json:/usr/src/app/json
    restart: unless-stopped
    networks:
      - apinet
    environment:
      - CONFIG=config

networks:
  apinet:
    external: true
    name: chromejobs_apinet