version: "3.9"
services:
  chromelocal:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    restart: unless-stopped
    environment:
      - SE_NODE_MAX_SESSIONS=100
      - SE_SESSION_REQUEST_TIMEOUT=86400
      - SE_NODE_SESSION_TIMEOUT=86400
    expose:
      - "4444"
    networks:
      fastnet:
        ipv4_address: 192.168.50.3

  fastjobs:
    build: .
    volumes:
      - ./json:/usr/src/app/json
    depends_on:
      - chromelocal
    restart: unless-stopped
    environment:
      - CONFIG=config
    networks:
      - fastnet

networks:
  fastnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24
